prometheusUrl: https://prom.andrei.lan

trackChannels:
  - channelId: 1394686399839731782
    name: "Memory usage: {Memory Usage}"
  - channelId: 1394686421373288468
    name: "CPU usage: {CPU Usage}"
  - channelId: 1394695038038184078
    name: "Network in: {Network in}"
  - channelId: 1394695049392029727
    name: "Network out: {Network out}"

metrics:
  - name: Memory Usage
    query: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100
    format: percentage
  - name: CPU Usage
    query: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100)
    format: percentage
  - name: Network in
    query: sum(rate(node_network_receive_bytes_total[1m])*8)
    format: dataspeed
  - name: Network out
    query: sum(rate(node_network_transmit_bytes_total[1m])*8)
    format: dataspeed

logTracking:
  - channelId: 1395816967981633668
    lokiInstance: 192.168.0.162:3100
    query: >
      {job="caddy"}
      | json
      | json forwarded=`request.headers["X-Forwarded-For"][0]`
      | json country=`request.headers["Cf-Ipcountry"][0]`
      | json user_agent=`request.headers["User-Agent"][0]`
      | country != "RO"
      | line_format "{{.ts}} | {{.request_method}} | {{.forwarded}} [{{.country}}] -> {{.request_remote_ip}} -> {{.request_host}} | {{.status}} | {{.duration}}s | {{.user_agent}}"
